# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Peekm < Formula
  desc "Zen-like markdown viewer with live reload"
  homepage "https://github.com/razvandimescu/peekm"
  version "0.1.11"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/razvandimescu/peekm/releases/download/v0.1.11/peekm_0.1.11_darwin_amd64.tar.gz"
      sha256 "84a35c1baadf1eafcb37e8f5c917a91274cb821971412ee38787968db7eef482"

      define_method(:install) do
        bin.install "peekm"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/razvandimescu/peekm/releases/download/v0.1.11/peekm_0.1.11_darwin_arm64.tar.gz"
      sha256 "d8ddedaf87cfad335266d9e5327d41fa1498bf195cdc85e0d067c72bb9882b00"

      define_method(:install) do
        bin.install "peekm"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/razvandimescu/peekm/releases/download/v0.1.11/peekm_0.1.11_linux_amd64.tar.gz"
      sha256 "d296dbee541c3e70e357013c25bce6d3bea6c3b75e11ed54fc2ba3d4f7f8109c"
      define_method(:install) do
        bin.install "peekm"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/razvandimescu/peekm/releases/download/v0.1.11/peekm_0.1.11_linux_arm64.tar.gz"
      sha256 "320a3e62af9d957081699651e5b558f5b1fe5a78e3dc602a5f0e0999874695e1"
      define_method(:install) do
        bin.install "peekm"
      end
    end
  end

  test do
    system "#{bin}/peekm", "--version"
  end
end
