# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Peekm < Formula
  desc "Track every AI coding session across all your projects in real time"
  homepage "https://github.com/razvandimescu/peekm"
  version "0.1.31"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/razvandimescu/peekm/releases/download/v0.1.31/peekm_0.1.31_darwin_amd64.tar.gz"
      sha256 "3bcb2ce9bad88e771f11e08c2fc126a23e132821810c0fe82a441e0962ebaf4d"

      define_method(:install) do
        bin.install "peekm"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/razvandimescu/peekm/releases/download/v0.1.31/peekm_0.1.31_darwin_arm64.tar.gz"
      sha256 "bec97070a473752332d1b25c7ead35c0663214444cb04c1c052d212884558359"

      define_method(:install) do
        bin.install "peekm"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/razvandimescu/peekm/releases/download/v0.1.31/peekm_0.1.31_linux_amd64.tar.gz"
      sha256 "2329c43dcce82e158574c136f887d8de2d8689af68562fb4633cc1f548c914fd"
      define_method(:install) do
        bin.install "peekm"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/razvandimescu/peekm/releases/download/v0.1.31/peekm_0.1.31_linux_arm64.tar.gz"
      sha256 "c53ea5b22a8bd785181154d0a2c465ee2c79486d37ff4468853aa321c2c7e792"
      define_method(:install) do
        bin.install "peekm"
      end
    end
  end

  test do
    system "#{bin}/peekm", "--version"
  end
end
