# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Peekm < Formula
  desc "Track every AI coding session across all your projects in real time"
  homepage "https://github.com/razvandimescu/peekm"
  version "0.1.21"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/razvandimescu/peekm/releases/download/v0.1.21/peekm_0.1.21_darwin_amd64.tar.gz"
      sha256 "4af7891aa2f7ff43fc0aedbe53bf425936a9737d1ae2be1d7921aca4c5ad90e5"

      define_method(:install) do
        bin.install "peekm"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/razvandimescu/peekm/releases/download/v0.1.21/peekm_0.1.21_darwin_arm64.tar.gz"
      sha256 "025db9f979d46fc51d13c91e95f6c4cb02c8f30d2190690f770a4cfcc2da7304"

      define_method(:install) do
        bin.install "peekm"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/razvandimescu/peekm/releases/download/v0.1.21/peekm_0.1.21_linux_amd64.tar.gz"
      sha256 "b85b8e8ff03ada63665853a9301684cd68895ee5dd867eefd72d96abb60f4a35"
      define_method(:install) do
        bin.install "peekm"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/razvandimescu/peekm/releases/download/v0.1.21/peekm_0.1.21_linux_arm64.tar.gz"
      sha256 "12ba2b9a1f9996ab08e10b980e4a7dd3ca9347228cb59610e42d22407a396eae"
      define_method(:install) do
        bin.install "peekm"
      end
    end
  end

  test do
    system "#{bin}/peekm", "--version"
  end
end
