# This file was generated by GoReleaser. DO NOT EDIT.
cask "peekm" do
  name "peekm"
  desc "Zen-like markdown viewer with live reload"
  homepage "https://github.com/razvandimescu/peekm"
  version "0.1.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "peekm"

  on_macos do
    on_intel do
      url "https://github.com/razvandimescu/peekm/releases/download/v#{version}/peekm_#{version}_darwin_amd64.tar.gz"
      sha256 "4c30e7bbde38644ab32c733780c3f2bbd73b16080cab67b0565ff3f10a8be1d7"
    end
    on_arm do
      url "https://github.com/razvandimescu/peekm/releases/download/v#{version}/peekm_#{version}_darwin_arm64.tar.gz"
      sha256 "64c4fa803989e162cdcb939360e70d1bb199a4b5e16f49b27ac7f0f73911f17f"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/razvandimescu/peekm/releases/download/v#{version}/peekm_#{version}_linux_amd64.tar.gz"
      sha256 "e9e596a01f866e318acbb3dc9e9d33e4c5b0efbcb54b871a51c2ee3f396b53a7"
    end
    on_arm do
      url "https://github.com/razvandimescu/peekm/releases/download/v#{version}/peekm_#{version}_linux_arm64.tar.gz"
      sha256 "b90fca9baf7fa382dcc07b4dda999540fbb49634f6da2fe8cff33a0a74f60e16"
    end
  end

  # No zap stanza required
end
